on:
  workflow_dispatch:  # Manually triggered

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Apache JMeter
      run: |
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xf apache-jmeter-5.6.3.tgz

    - name: Run JMeter test
      run: |
        cd apache-jmeter-5.6.3/bin
        ./jmeter -n -t ../../HTTP-Request-CXF.jmx -l test-results.jtl -l jmeter.log -e -o test-report

    - name: Upload JTL file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: JMeter Test Results
        path: apache-jmeter-5.6.3/bin/test-results.jtl

    - name: Upload jmeter.log file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: JMeter Log File
        path: apache-jmeter-5.6.3/bin/jmeter.log

    - name: Upload HTML test report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: JMeter HTML Test Report
        path: apache-jmeter-5.6.3/bin/test-report
