on:
  workflow_dispatch:  # Manually triggered

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Apache JMeter
      run: |
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xf apache-jmeter-5.6.3.tgz

    - name: Run JMeter test
      run: |
        cd apache-jmeter-5.6.3/bin
        ./jmeter -n -t ../../HTTP-Request-CXF.jmx -l test-results.jtl

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v2
      with:
        name: JMeter Performance Test
        path: apache-jmeter-5.6.3/bin/test-results.jtl
